### PR TITLE
odd spacing needed

### PR DESCRIPTION
**Pull request by wallasfmorais**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by wallasfmorais** [comment]
@mcollina, hey man. So, I probably finish the README.md. Idk how or who can review. 

I saw, if I aren't wrong,  some guys gived start that maybe are Brazilian or Portuguese.

I will continue translating docs inner files and will only push when I finish and get almost sure about the accuracy about each one of it.

And when I finish then all I add the link on the English version to it.

**Comment by RafaelGSS** [comment]
Hello @wallasfmorais I'll help you in the translation, can mark me in the PRs? I'll do it too

**Comment by wallasfmorais** [comment]
Awesome. @RafaelGSS. I'll accept yours PR, but IDK if I've permissions enough to add you to automatically do that yourself.

**Comment by RafaelGSS** [comment]
Yes, I have. But, can be good a review.

**Pull request merged**
